### ISSUE TITLE
srv2 testing

### ISSUE THREAD

**Issue by mahnouman** [k8-proxy/go-k8s-srv2#4]
Please build and test the code in this repo as per the instructions in the readme file, please take note of missing steps or whenever you get stuck.

Please provide a thorough and detailed response to this issue with your findings.

**Comment by haitham911** [comment]
I can't run this test because  you don't explain :
how deploy rabbitmq , Minio and which version
how configure rabbitmq , Minio to work with go-k8s-srv2
and how I get this variable 
docker run -e ADAPTATION_REQUEST_QUEUE_HOSTNAME='' \
-e ADAPTATION_REQUEST_QUEUE_PORT=''
-e MESSAGE_BROKER_USER=''
-e MESSAGE_BROKER_PASSWORD=''
-e MINIO_ENDPOINT='' \
-e MINIO_ACCESS_KEY='' \
-e MINIO_SECRET_KEY='' \
-e MINIO_SOURCE_BUCKET='' \
--name <docker_container_name> <docker_image_name>
